PRAGMA foreign_keys = ON;

DROP TABLE IF EXISTS passengers;
DROP TABLE IF EXISTS lineSegments;
DROP TABLE IF EXISTS stopLines;
DROP TABLE IF EXISTS lines;
DROP TABLE IF EXISTS stops;

CREATE TABLE stops(
	name VARCHAR(50) PRIMARY KEY
);

CREATE TABLE lines(
	name VARCHAR(50) PRIMARY KEY,
	firstStop VARCHAR(50) NOT NULL REFERENCES stops(name) ON DELETE RESTRICT ON UPDATE CASCADE
);

CREATE TABLE stopLines(
	stop VARCHAR(50) NOT NULL REFERENCES stops(name) ON DELETE RESTRICT ON UPDATE CASCADE,
	line VARCHAR(50) NOT NULL REFERENCES lines(name) ON DELETE RESTRICT ON UPDATE CASCADE,
	UNIQUE (stop, line)
);

CREATE TABLE lineSegments(
	lineName VARCHAR(50) NOT NULL REFERENCES lines(name) ON DELETE RESTRICT ON UPDATE CASCADE,
	sIndex INTEGER NOT NULL,
	duration INTEGER NOT NULL,
	capacity INTEGER NOT NULL,
	nextStop VARCHAR(50) NOT NULL REFERENCES stops(name) ON DELETE RESTRICT ON UPDATE CASCADE,
	UNIQUE (lineName, sIndex),
	CHECK (duration > 0 AND capacity > 0)
);

CREATE TABLE passengers(
	lineName VARCHAR(50) NOT NULL REFERENCES lines(name) ON DELETE RESTRICT ON UPDATE CASCADE,
	sIndex INTEGER NOT NULL REFERENCES lineSegments(sIndex) ON DELETE RESTRICT ON UPDATE CASCADE,
	time INTEGER NOT NULL,
	pCount INTEGER NOT NULL,
	CHECK (time >= 0 AND pCount >= 0)
);
